### ISSUE TITLE
[Feat] Upadte on visualization

### ISSUE THREAD

**Issue by yoonjongyeon** [yehyunsuh/TEM-Image-Segmentation#12]
## What
Update visualization.py

## Why
To understand which parts of the image the model fails to predict.

## TODO
- [x] Mark pixels in blue where the model predicts but shouldn't have. (FP error)
- [x] Mark pixels in red where the model fails to predict but should have. (FN error)
- [x] Blend it with the original image.

**Comment by yoonjongyeon** [comment]
https://github.com/yehyunsuh/TEM-Image-Segmentation/blob/6fe6242842fd0c656d689c519a033d21eaf673c8/visualization.py#L79-L114

Added function to show FP error in blue and FN error in red.

**Comment by yoonjongyeon** [comment]
![image](https://github.com/yehyunsuh/TEM-Image-Segmentation/assets/90745298/3a3f5b45-da41-4cf9-acb7-fb4c21b79558)

Show that it shows FN errors and FP errors well.
